using VectorStudyCase.src;
using NUnit.Framework;
using System.Diagnostics;
using VectorStudyCase.src.Features;
using VectorStudyCase.src.Interfaces;

namespace TestProject
{
    public class Tests
    {

        //specify type of data that is used by my search engine
        public StringSearchEngine MySearchEngine { get; private set;}

        //specify which type of data i will traverse
        public List<ISearchStructure<string>> MyInputList { get; private set; }

        public List<ISearchStructure<string>> AutogeneratedInoutTestList { get; private set; }

        private Stopwatch _stopWatch = new Stopwatch();

        [SetUp]
        public void Setup()
        {
            MySearchEngine = new StringSearchEngine();

            //specify and fill with concrete stringsearchedstructure elements in list
            MyInputList = new List<ISearchStructure<string>> { new StringSearchedStructure("AAAA"), new StringSearchedStructure("ACZM"), new StringSearchedStructure("ANDY"), new StringSearchedStructure("AAAA"), new StringSearchedStructure("ACZM"), new StringSearchedStructure("ANDY") };

            GenerateAndShuffleMyVectorTestList();
        }

        private void GenerateAndShuffleMyVectorTestList()
        {
            AutogeneratedInoutTestList = new List<ISearchStructure<string>>();

            for (char firstLetter = 'A'; firstLetter <= 'Z'; firstLetter++)
            {
                for (char secondLetter = 'A'; secondLetter <= 'Z'; secondLetter++)
                {
                    for (char thirdLetter = 'A'; thirdLetter <= 'Z'; thirdLetter++)
                    {
                        for (char fourthLetter = 'A'; fourthLetter <= 'Z'; fourthLetter++)
                        {
                            string combination = $"{firstLetter}{secondLetter}{thirdLetter}{fourthLetter}";
                            AutogeneratedInoutTestList.Add(new StringSearchedStructure(combination));
                        }
                    }
                }
            }

            // Shuffle the word list to make the order random
            Random rng = new Random();
            int n = AutogeneratedInoutTestList.Count;
            while (n > 1)
            {
                n--;
                int k = rng.Next(n + 1);
                var value = AutogeneratedInoutTestList[k];
                AutogeneratedInoutTestList[k] = AutogeneratedInoutTestList[n];
                AutogeneratedInoutTestList[n] = value;
            }
        }

        [Test]
        public void Test1()
        {
            var testResults = MySearchEngine.SearchForPatternNonTrivial(MyInputList, new StringSearchedStructure("AN"));
            testResults.ForEach(x => Console.WriteLine(x));
            Assert.IsTrue(testResults.Count == 2 && testResults.Contains("ANDY"));
        }

        [Test]
        public void Test2()
        {
            _stopWatch.Start();
            var ReturnData = MySearchEngine.SearchForPatternTrivial(MyInputList, new StringSearchedStructure("AN"));
            _stopWatch.Stop();

            ReturnData.ForEach(x => Console.WriteLine(x));

            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsTrue(ReturnData.Count == 2 && ReturnData.Contains("ANDY"));
        }

        [Test]
        public void Test3()
        {
            _stopWatch.Start();
            var ReturnData = MySearchEngine.SearchForPatternNonTrivial(MyInputList, new StringSearchedStructure("MH"));
            _stopWatch.Stop();
            ReturnData.ForEach(x => Console.WriteLine(x));

            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsFalse(ReturnData.Count == 2 && ReturnData.Contains("ANDY"));
        }

        [Test]
        public void Test4()
        {
            MyInputList = new();
            _stopWatch.Start();
            var ReturnData = MySearchEngine.SearchForPatternNonTrivial(MyInputList, new StringSearchedStructure("MH"));
            _stopWatch.Stop();
            ReturnData.ForEach(x => Console.WriteLine(x));

            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsFalse(ReturnData.Count == 2 && ReturnData.Contains("ANDY"));
        }


        [Test]
        public void Test5()
        {
            Random random = new Random();
            int randomIndex = random.Next(0, AutogeneratedInoutTestList.Count);
            var randomElement = AutogeneratedInoutTestList[randomIndex];

            _stopWatch.Start();
            var testResults = MySearchEngine.SearchForPatternNonTrivial(AutogeneratedInoutTestList, randomElement);
            _stopWatch.Stop();

            testResults.ForEach(x => Console.WriteLine(x));
            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsTrue(testResults.Count == 1 && testResults.Contains(randomElement.Data!));

        }

        [Test]
        public void Test6()
        {
            Random random = new Random();
            int randomIndex = random.Next(0, AutogeneratedInoutTestList.Count);
            var randomElement = AutogeneratedInoutTestList[randomIndex];

            _stopWatch.Start();
            var testResults = MySearchEngine.SearchForPatternNonTrivial(AutogeneratedInoutTestList, randomElement);
            _stopWatch.Stop();

            testResults.ForEach(x => Console.WriteLine(x));
            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsTrue(testResults.Count == 1 && testResults.Contains(randomElement.Data!));

        }

        [Test]
        public void Test7()
        {
            Random random = new Random();
            int randomIndex = random.Next(0, AutogeneratedInoutTestList.Count);
            var randomElement = AutogeneratedInoutTestList[randomIndex];

            _stopWatch.Start();
            var testResults = MySearchEngine.SearchForPatternNonTrivial(AutogeneratedInoutTestList, randomElement);
            _stopWatch.Stop();

            testResults.ForEach(x => Console.WriteLine(x));
            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsTrue(testResults.Count == 1 && testResults.Contains(randomElement.Data!));

        }

        [Test]
        public void Test8()
        {
            Random random = new Random();
            int randomIndex = random.Next(0, AutogeneratedInoutTestList.Count);
            var randomElement = AutogeneratedInoutTestList[randomIndex];

            _stopWatch.Start();
            var testResults = MySearchEngine.SearchForPatternTrivial(AutogeneratedInoutTestList, randomElement);
            _stopWatch.Stop();

            testResults.ForEach(x => Console.WriteLine(x));
            Console.WriteLine($"elapsed time iin microseconds taken here is {_stopWatch.ElapsedTicks / 10.0}");

            Assert.IsTrue(testResults.Count == 1 && testResults.Contains(randomElement.Data!));

        }


    }
}